//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReservationSystem.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookManagementEntities2 : DbContext
    {
        public BookManagementEntities2()
            : base("name=BookManagementEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Book> T_Book { get; set; }
        public virtual DbSet<T_BookToBePurchased> T_BookToBePurchased { get; set; }
        public virtual DbSet<T_Notification> T_Notification { get; set; }
        public virtual DbSet<T_Order> T_Order { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_Test> T_Test { get; set; }
        public virtual DbSet<T_LackBooks> T_LackBooks { get; set; }
    }
}
