//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReservationSystem.Entities
{
    using System;
    
    public enum LackBooksStatus : short
    {
        /// <summary>
        /// 正在采购
        /// </summary>
        BeingProcured = 0,
        /// <summary>
        /// 未处理
        /// </summary>
        Unhandled = 1,
        /// <summary>
        /// 拒绝
        /// </summary>
        Rejected = 2
    }
}
