//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReservationSystem.Entities
{
    using System;
    
    public enum NotificationStatus : short
    {
        /// <summary>
        /// 已读并同意
        /// </summary>
        Read = 0,
        /// <summary>
        /// 未读
        /// </summary>
        NotRead = 1,
        /// <summary>
        /// 拒绝
        /// </summary>
        Reject = 2
    }
}
