//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookReservationSystem.Entities
{
    using System;
    
    public enum OrderStatus : short
    {
        Completed = 0,
        OutOfStock = 1,
        Unhandled = 2,
        Rejected = 3
    }
}
